//
//  LCHStyleKit.h
//  LCH
//
//  Created by JOSE MARTINEZ on 09/03/2015.
//  Copyright (c) 2015 Brightec. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* tickCircleTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* insuranceTargets;

// Drawing Methods
+ (void)drawTickCircle;
+ (void)drawInsurance;

// Colors
+ (void)setDesiredFillColor:(UIColor*)color;
+ (UIColor*)desiredFillColor;

@end
